<?php

namespace mrmuminov\printpagegenerator\controllers;

use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * @package @mrmuminov\printpagegenerator
 * @author Bahriddin Mo'minov
 * @email darkshadeuz@gmail.com
 * @site https://bahriddin.uz
 */
class MakeController extends Controller
{
    public $saveAction = 'save-action';
    public function beforeAction($action)
    {
        if (ArrayHelper::isIn($action->id, ['make', 'print'])) {
            $this->viewPath = "@vendor/mrmuminov/yii2-print-page-generator/views/make";
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionMake($w, $h)
    {
        $staticVariables = [];
        if (method_exists(static::class, 'staticVariables')) {
            $staticVariables = static::staticVariables();
        }
        $dynamicVariables = [];
        if (method_exists(static::class, 'dynamicVariables')) {
            $dynamicVariables = static::dynamicVariables();
        }

        return $this->render('make.php', [
            'w' => $w,
            'h' => $h,
            'staticVariables' => $staticVariables,
            'dynamicVariables' => $dynamicVariables,
            'saveAction' => $this->saveAction,
        ]);
    }
}